config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create]
  resources :songs

  # resources :categories, only: [:index] do
  #   resources :articles, except: [:destroy]
  # end

  # get '/rounds/:id/next_card', to: 'rounds#next_card', as: "next_card"
  get '/logout', to: 'sessions#destroy'

  root 'songs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user, optional: true
  validates :title, :artist, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  validates :username, presence: true
  has_secure_password

  has_many :songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      @errors = ["Something bad happened"]
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :redirect_unless_logged_in, except: [:index, :show]
  before_action :find_song, only: [:show, :edit, :update, :destroy]
  before_action -> { redirect_unless_owner(@song.user) }, only: [:edit, :update, :destroy]

  def index
    @songs = Song.all
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      current_user.songs << @song
      redirect_to root_path
    else
      @errors = @song.errors.full_messages
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to root_path
    else
      @errors = @song.errors.full_messages
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to root_path
  end

  private

  def song_params
    params.require(:song).permit(:title, :artist)
  end

  def find_song
    @song = Song.find_by(id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  def new
   @user = User.new
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    session[:user_id] != nil
  end

  def redirect_unless_logged_in
    redirect_to new_session_path unless logged_in?
  end

  def redirect_unless_owner(user)
    redirect_to root_path unless current_user == user
  end

  def authorized?(user)
    current_user == user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Breakout</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <nav>
        <h1><%= link_to "Songs!", root_path %></h1>
        <ul>
          <% if logged_in? %>
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Logout", logout_path %></li>
          <% else %>
          <li><%= link_to "Login", new_session_path %></li>
          <li><%= link_to "Sign up", new_user_path, id: "sign_up", class: "thing" %></li>
          <% end %>
        </ul>
      </nav>
      <div class="main">
      <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<ul>
  <% errors.each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>

app/views/songs/_form.html.erb
<%= render partial: "shared/errors", locals: {errors: @errors} if @errors %>
<%= form_for(@song) do |f| %>
  <%= f.text_field :title, placeholder: "title" %>
  <%= f.text_field :artist, placeholder: "artist" %>
  <%= submit_tag  %>
<% end %>

app/views/songs/_song.html.erb
<li><%= link_to song.title, song %> - <%= song.artist %></li>

app/views/songs/edit.html.erb
<h2>Edit Song</h2>

<%= render "form" %>

app/views/songs/index.html.erb
<ul>
<%= render @songs %>
</ul>

app/views/songs/new.html.erb
<h2>Create Song</h2>

<%= render "form" %>

app/views/songs/show.html.erb
<h2><%= @song.title %></h2>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= render partial: "shared/errors", locals: {errors: @errors} if @errors %>
<%= form_for(@user) do |f| %>
  <%= f.text_field :username, placeholder: "username" %>
  <%= f.password_field :password, placeholder: "password" %>
  <%= submit_tag  %>
<% end %>